version: '2'

services:
  dockerindividualauth:
    image: user/dockerindividualauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9071:80"
    depends_on:
      - dockerindividualauth.db
  dockerindividualauth.db:
    image: postgres